# Generated by Django 4.0.2 on 2022-03-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_alter_myuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_seller',
        ),
    ]
