# Generated by Django 4.0.2 on 2022-03-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc_forum', '0002_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
